/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication3;

import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author labinf6.pasto
 */
public class NpcForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NpcForm.class.getName());

    /**
     * Creates new form NpcForm
     */
    private final DefaultListModel<Npc> npcListModel = new DefaultListModel<>();
    private final NpcDirector director = new NpcDirector();
    private final NpcBuilder builder = new DefaultNpcBuilder();

    public NpcForm() {
        initComponents();
        initializeCustomUi();
        bindEvents();
    }

    private void initializeCustomUi() {
        typeNpc.setModel(new DefaultComboBoxModel<>(new String[] {
            "Basic Soldier", "Elite Soldier", "Archer"
        }));

        npcs.setModel(npcListModel);
        details.setEditable(false);
        details.setLineWrap(true);
        details.setWrapStyleWord(true);
    }

    private void bindEvents() {
        createBase.addActionListener(evt -> createBaseNpc());
        cloneSelected.addActionListener(evt -> cloneSelectedNpc());
        npcs.addListSelectionListener(evt -> {
            if (!evt.getValueIsAdjusting()) {
                showDetails(npcs.getSelectedValue());
            }
        });
    }

    private void createBaseNpc() {
        String baseName = name.getText().trim();
        String type = (String) typeNpc.getSelectedItem();

        if (baseName.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an NPC name.");
            return;
        }

        Npc npc;
        switch (type) {
            case "Elite Soldier":
                npc = director.createEliteSoldier(builder, baseName);
                break;
            case "Archer":
                npc = director.createArcher(builder, baseName);
                break;
            case "Basic Soldier":
            default:
                npc = director.createBasicSoldier(builder, baseName);
                break;
        }

        npcListModel.addElement(npc);
        npcs.setSelectedValue(npc, true);
    }

    private void cloneSelectedNpc() {
        Npc selected = npcs.getSelectedValue();
        if (selected == null) {
            JOptionPane.showMessageDialog(this, "Select an NPC first.");
            return;
        }

        Npc clone = selected.copy();
        clone.setName(selected.getName() + "-copy-" + (npcListModel.getSize() + 1));

        npcListModel.addElement(clone);
        npcs.setSelectedValue(clone, true);
    }

    private void showDetails(Npc npc) {
        if (npc == null) {
            details.setText("");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("Name: ").append(npc.getName()).append('\n');
        sb.append("Life Points: ").append(npc.getLifePoints()).append('\n');
        sb.append("Damage Points: ").append(npc.getDamagePoints()).append('\n');
        sb.append("Abilities:\n");

        for (Ability ability : npc.getAbilities()) {
            sb.append("- ").append(ability.getName()).append('\n');
        }

        details.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JTextField();
        typeNpc = new javax.swing.JComboBox<>();
        createBase = new javax.swing.JButton();
        cloneSelected = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        npcs = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        details = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setText("Name");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });

        typeNpc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        typeNpc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeNpcActionPerformed(evt);
            }
        });

        createBase.setText("create Npc");
        createBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBaseActionPerformed(evt);
            }
        });

        cloneSelected.setText("clone");

        jScrollPane1.setViewportView(npcs);

        details.setColumns(20);
        details.setRows(5);
        jScrollPane2.setViewportView(details);

        jLabel1.setText("Name of NPC");

        jLabel2.setText("Npcs");

        jLabel3.setText("Type of Npc");

        jLabel4.setText("Details of the Npc");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(typeNpc, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(createBase)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cloneSelected)
                        .addGap(16, 16, 16))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(name, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(182, 182, 182)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(2, 2, 2)
                .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(createBase)
                            .addComponent(cloneSelected))
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(typeNpc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(46, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void typeNpcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeNpcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeNpcActionPerformed

    private void createBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createBaseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new NpcForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cloneSelected;
    private javax.swing.JButton createBase;
    private javax.swing.JTextArea details;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField name;
    private javax.swing.JList<Npc> npcs;
    private javax.swing.JComboBox<String> typeNpc;
    // End of variables declaration//GEN-END:variables
}
